on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    using: 'composite'
    steps:
      - uses: actions/checkout@v2
      - run: npm i
        shell: bash
      - run: npm ci
        shell: bash
      - run: npm run build
        shell: bash
